"""novo campo descricao

Revision ID: 75da0b7266f5
Revises: 76ae17b6c119
Create Date: 2024-12-01 20:29:41.776168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75da0b7266f5'
down_revision = '76ae17b6c119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carona', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
