"""tabelas carros

Revision ID: 76ae17b6c119
Revises: 
Create Date: 2024-11-30 17:29:45.140123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ae17b6c119'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('horario', sa.String(length=255), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('localidade', sa.String(length=255), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carona')
    op.drop_table('user')
    # ### end Alembic commands ###
