"""carona passageiros

Revision ID: c269f0a5bacc
Revises: 75da0b7266f5
Create Date: 2024-12-02 16:57:48.278902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c269f0a5bacc'
down_revision = '75da0b7266f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carona_passageiros',
    sa.Column('carona_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carona_id'], ['carona.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('carona_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carona_passageiros')
    # ### end Alembic commands ###
